<a href="https://colab.research.google.com/github/Roberto014/Anal-tica-de-datos-y-herramientas-de-inteligencia-artificial-II/blob/main/ACTIVIDADBASE%20DE%20DATOSAIRBUntitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
files.upload()

In [10]:
data=pd.read_csv("listings.csv")
data.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,898633,https://www.airbnb.com/rooms/898633,20240627045222,2024-06-28,city scrape,City SkyLine View from 1 Bedroom Apt in CDMX,The LOCATION is undoubtedly THE BIG advantage ...,The hipster Roma neighborhood embodies a color...,https://a0.muscache.com/pictures/ba75b1c1-cb02...,4796027,...,4.96,4.93,4.91,NaN,f,3,2,1,0,0.41
1,35797,https://www.airbnb.com/rooms/35797,20240627045222,2024-06-27,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Mall, Interloma Park and the Lion Des...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2,44616,https://www.airbnb.com/rooms/44616,20240627045222,2024-06-28,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.48,NaN,f,13,4,2,0,0.42
3,913084,https://www.airbnb.com/rooms/913084,20240627045222,2024-06-28,city scrape,15 blocks from Paseo de la Reforma,NaN,"It borders the old and traditional San Rafael,...",https://a0.muscache.com/pictures/16663562/7bed...,4647293,...,4.93,4.46,4.75,NaN,t,1,1,0,0,1.19
4,67703,https://www.airbnb.com/rooms/67703,20240627045222,2024-06-28,city scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.91,NaN,f,2,2,0,0,0.32

In [22]:
#Eliminar columnas
data.drop(columns=['host_url'], inplace=True)

KeyError: "['host_url'] not found in axis"

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 62 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   scrape_id                                     26536 non-null  int64
 1   last_scraped                                  26536 non-null  object
 2   source                                        26536 non-null  object
 3   name                                          26536 non-null  object
 4   description                                   25585 non-null  object
 5   host_id                                       26536 non-null  int64
 6   host_name                                     26536 non-null  object
 7   host_since                                    26536 non-null  object
 8   host_location                                 20930 non-null  object
 9   host_response_time                            22339 non-null  object
 10  host_response_rate                            22339 non-null  object
 11  host_acceptance_rate                          23681 non-null  object
 12  host_is_superhost                             24993 non-null  object
 13  host_listings_count                           26536 non-null  int64
 14  host_total_listings_count                     26536 non-null  int64
 15  host_verifications                            26536 non-null  object
 16  host_has_profile_pic                          26536 non-null  object
 17  host_identity_verified                        26536 non-null  object
 18  neighbourhood_cleansed                        26536 non-null  object
 19  latitude                                      26536 non-null  float64
 20  longitude                                     26536 non-null  float64
 21  property_type                                 26536 non-null  object
 22  room_type                                     26536 non-null  object
 23  accommodates                                  26536 non-null  int64
 24  bathrooms                                     23407 non-null  float64
 25  bathrooms_text                                26511 non-null  object
 26  bedrooms                                      25465 non-null  float64
 27  beds                                          23372 non-null  float64
 28  amenities                                     26536 non-null  object
 29  price                                         23338 non-null  object
 30  minimum_nights                                26536 non-null  int64
 31  maximum_nights                                26536 non-null  int64
 32  minimum_minimum_nights                        26536 non-null  int64
 33  maximum_minimum_nights                        26536 non-null  int64
 34  minimum_maximum_nights                        26536 non-null  int64
 35  maximum_maximum_nights                        26536 non-null  int64
 36  minimum_nights_avg_ntm                        26536 non-null  float64
 37  maximum_nights_avg_ntm                        26536 non-null  float64
 38  has_availability                              25500 non-null  object
 39  availability_30                               26536 non-null  int64
 40  availability_60                               26536 non-null  int64
 41  availability_90                               26536 non-null  int64
 42  availability_365                              26536 non-null  int64
 43  calendar_last_scraped                         26536 non-null  object
 44  number_of_reviews                             26536 non-null  int64
 45  number_of_reviews_ltm                         26536 non-null  int64
 46  number_of_reviews_l30d                        26536 non-null  int64
 47  first_review                                  22664 non-null  object
 48  last_review                                   22664 non-null  object
 49  review_scores_rating                          22664 non-null  float64
 50  review_scores_accuracy                        22649 non-null  float64
 51  review_scores_cleanliness                     22648 non-null  float64
 52  review_scores_checkin                         22649 non-null  float64
 53  review_scores_communication                   22649 non-null  float64
 54  review_scores_location                        22649 non-null  float64
 55  review_scores_value                           22649 non-null  float64
 56  instant_bookable                              26536 non-null  object
 57  calculated_host_listings_count                26536 non-null  int64
 58  calculated_host_listings_count_entire_homes   26536 non-null  int64
 59  calculated_host_listings_count_private_rooms  26536 non-null  int64
 60  calculated_host_listings_count_shared_rooms   26536 non-null  int64
 61  reviews_per_month                             22664 non-null  float64
dtypes: float64(15), int64(22), object(25)
memory usage: 12.6+ MB

In [25]:
data.shape

(26536, 62)

In [98]:
valores_nulos = data2.isnull().sum()
valores_nulos

scrape_id                                       0
last_scraped                                    0
source                                          0
name                                            0
description                                     0
                                               ..
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
Length: 62, dtype: int64

In [36]:
data.head(5)

,scrape_id,last_scraped,source,name,description,host_id,host_name,host_since,host_location,host_response_time,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,20240627045222,2024-06-28,city scrape,City SkyLine View from 1 Bedroom Apt in CDMX,The LOCATION is undoubtedly THE BIG advantage ...,4796027,Marco,2013-01-21,"Mexico City, Mexico",within an hour,...,4.93,4.96,4.93,4.91,f,3,2,1,0,0.41
1,20240627045222,2024-06-27,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...",153786,Dici,2010-06-28,"Mexico City, Mexico",a few days or more,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2,20240627045222,2024-06-28,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,196253,Fernando,2010-08-09,"Mexico City, Mexico",within an hour,...,4.87,4.78,4.98,4.48,f,13,4,2,0,0.42
3,20240627045222,2024-06-28,city scrape,15 blocks from Paseo de la Reforma,NaN,4647293,Martina,2013-01-09,"Mexico City, Mexico",within an hour,...,4.84,4.93,4.46,4.75,t,1,1,0,0,1.19
4,20240627045222,2024-06-28,city scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",334451,Nicholas,2011-01-04,"Mexico City, Mexico",within a day,...,4.94,4.92,4.98,4.91,f,2,2,0,0,0.32

##RELLENO DE DATOS DE TIPO STRING

In [38]:
data2=data.copy()

In [40]:
data2["host_location"] =data2["host_location"].fillna("No se encuentra localizacion")

In [95]:
data2["description"] =data2["description"].fillna("No se encuentra la descripción")

In [59]:
data2["host_response_time"] =data2["host_response_time"].fillna("No se encuentra la hora")

In [60]:
data2["host_is_superhost"] =data2["host_is_superhost"].fillna("Desconocido")

In [62]:
data2["bathrooms_text"] =data2["bathrooms_text"].fillna("No hay descripción")

In [77]:
data2["has_availability"] =data2["has_availability"].fillna("No hay descripción")

In [78]:
data2["first_review"] =data2["first_review"].fillna("No hay fecha")
#first_review

In [79]:
data2["last_review"] =data2["last_review"].fillna("No hay fecha")
#last_review

##RELLENO DE DATOS DE TIPO FLOAT O ENTERO

de la columna host_response_rate convierte todos los valores a valor tipo entero

In [47]:
data2["host_response_rate"] =data2["host_response_rate"].str.replace('%','')

In [51]:
data2["host_response_rate"] = data2["host_response_rate"].astype(float)

In [52]:
data2["host_response_rate"]=data2["host_response_rate"].fillna(round(data2["host_response_rate"].mean(),1))

In [54]:
data2["host_acceptance_rate"] =data2["host_acceptance_rate"].str.replace('%','')

In [56]:
data2["host_acceptance_rate"] = data2["host_acceptance_rate"].astype(float)

In [57]:
data2["host_acceptance_rate"]=data2["host_acceptance_rate"].fillna(round(data2["host_acceptance_rate"].mean(),1))

In [61]:
data2["bathrooms"]=data2["bathrooms"].fillna(round(data2["bathrooms"].mean(),1))

In [63]:
data2["bedrooms"]=data2["bedrooms"].fillna(round(data2["bedrooms"].mean(),1))

In [64]:
data2["beds"]=data2["beds"].fillna(round(data2["beds"].mean(),1))

In [65]:
data2["price"] =data2["price"].str.replace('$','')

In [67]:
data2["price"] =data2["price"].str.replace(',','')

In [68]:
data2["price"] = data2["price"].astype(float)

In [71]:
data2["price"]=data2["price"].fillna(round(data2["price"].mean(),1))

In [76]:
data = data2.groupby(['price']) ['price'].count()
data

price
105.0       1
109.0       1
119.0       2
125.0       2
134.0       1
           ..
98128.0     1
100745.0    1
150000.0    1
274758.0    1
416684.0    1
Name: price, Length: 3446, dtype: int64

In [80]:
data2["review_scores_rating"]=data2["review_scores_rating"].fillna(round(data2["review_scores_rating"].mean(),1))
#review_scores_rating

In [82]:
data2["review_scores_accuracy"]=data2["review_scores_accuracy"].fillna(round(data2["review_scores_accuracy"].mean(),1))

In [83]:
data2["review_scores_cleanliness"]=data2["review_scores_cleanliness"].fillna(round(data2["review_scores_cleanliness"].mean(),1))
#review_scores_cleanliness

In [84]:
data2["review_scores_checkin"]=data2["review_scores_checkin"].fillna(round(data2["review_scores_checkin"].mean(),1))
#review_scores_checkin

In [85]:
data2["review_scores_communication"]=data2["review_scores_communication"].fillna(round(data2["review_scores_communication"].mean(),1))
#review_scores_communication

In [87]:
data2["review_scores_location"]=data2["review_scores_location"].fillna(round(data2["review_scores_location"].mean(),1))
#review_scores_location

In [88]:
data2["review_scores_value"]=data2["review_scores_value"].fillna(round(data2["review_scores_value"].mean(),1))

In [97]:
data2["reviews_per_month"]=data2["reviews_per_month"].fillna(round(data2["reviews_per_month"].mean(),1))
#reviews_per_month

In [110]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 62 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   scrape_id                                     26536 non-null  int64
 1   last_scraped                                  26536 non-null  object
 2   source                                        26536 non-null  object
 3   name                                          26536 non-null  object
 4   description                                   26536 non-null  object
 5   host_id                                       26536 non-null  int64
 6   host_name                                     26536 non-null  object
 7   host_since                                    26536 non-null  object
 8   host_location                                 26536 non-null  object
 9   host_response_time                            26536 non-null  object
 10  host_response_rate                            26536 non-null  float64
 11  host_acceptance_rate                          26536 non-null  float64
 12  host_is_superhost                             26536 non-null  object
 13  host_listings_count                           26536 non-null  int64
 14  host_total_listings_count                     26536 non-null  int64
 15  host_verifications                            26536 non-null  object
 16  host_has_profile_pic                          26536 non-null  object
 17  host_identity_verified                        26536 non-null  object
 18  neighbourhood_cleansed                        26536 non-null  object
 19  latitude                                      26536 non-null  float64
 20  longitude                                     26536 non-null  float64
 21  property_type                                 26536 non-null  object
 22  room_type                                     26536 non-null  object
 23  accommodates                                  26536 non-null  int64
 24  bathrooms                                     26536 non-null  float64
 25  bathrooms_text                                26536 non-null  object
 26  bedrooms                                      26536 non-null  float64
 27  beds                                          26536 non-null  float64
 28  amenities                                     26536 non-null  object
 29  price                                         26536 non-null  float64
 30  minimum_nights                                26536 non-null  int64
 31  maximum_nights                                26536 non-null  int64
 32  minimum_minimum_nights                        26536 non-null  int64
 33  maximum_minimum_nights                        26536 non-null  int64
 34  minimum_maximum_nights                        26536 non-null  int64
 35  maximum_maximum_nights                        26536 non-null  int64
 36  minimum_nights_avg_ntm                        26536 non-null  float64
 37  maximum_nights_avg_ntm                        26536 non-null  float64
 38  has_availability                              26536 non-null  object
 39  availability_30                               26536 non-null  int64
 40  availability_60                               26536 non-null  int64
 41  availability_90                               26536 non-null  int64
 42  availability_365                              26536 non-null  int64
 43  calendar_last_scraped                         26536 non-null  object
 44  number_of_reviews                             26536 non-null  int64
 45  number_of_reviews_ltm                         26536 non-null  int64
 46  number_of_reviews_l30d                        26536 non-null  int64
 47  first_review                                  26536 non-null  object
 48  last_review                                   26536 non-null  object
 49  review_scores_rating                          26536 non-null  float64
 50  review_scores_accuracy                        26536 non-null  float64
 51  review_scores_cleanliness                     26536 non-null  float64
 52  review_scores_checkin                         26536 non-null  float64
 53  review_scores_communication                   26536 non-null  float64
 54  review_scores_location                        26536 non-null  float64
 55  review_scores_value                           26536 non-null  float64
 56  instant_bookable                              26536 non-null  object
 57  calculated_host_listings_count                26536 non-null  int64
 58  calculated_host_listings_count_entire_homes   26536 non-null  int64
 59  calculated_host_listings_count_private_rooms  26536 non-null  int64
 60  calculated_host_listings_count_shared_rooms   26536 non-null  int64
 61  reviews_per_month                             26536 non-null  float64
dtypes: float64(18), int64(22), object(22)
memory usage: 12.6+ MB

In [ ]:
# Supongamos que tu DataFrame se llama 'data2'

# Paso 1: Seleccionar solo las columnas que tienen valores flotantes o enteros
columnas_numericas = data2.select_dtypes(include=['float', 'int'])

# Paso 2: Excluir algunas columnas que no quieres ver, por ejemplo, 'columna_a' y 'columna_b'
columnas_filtradas = columnas_numericas.drop(columns=['host_response_rate', 'host_acceptance_rate','bathrooms','bedrooms','beds','price','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','reviews_per_month'])

# Ver el resultado
print(columnas_filtradas.head())

In [121]:
# Supongamos que tu DataFrame se llama 'data2'

# Paso 1: Seleccionar solo las columnas que tienen valores flotantes o enteros
columnas_numericas = data2.select_dtypes(include=[object])

# Paso 2: Excluir algunas columnas que no quieres ver, por ejemplo, 'columna_a' y 'columna_b'
columnas_filtradas = columnas_numericas.drop(columns=['host_location','description','host_response_time','host_is_superhost','bathrooms_text','has_availability','first_review','last_review'])

# Ver el resultado
print(columnas_filtradas.head())

  last_scraped       source                                          name  \
0   2024-06-28  city scrape  City SkyLine View from 1 Bedroom Apt in CDMX
1   2024-06-27  city scrape                                   Villa Dante
2   2024-06-28  city scrape                             CONDESA HAUS  B&B
3   2024-06-28  city scrape            15 blocks from Paseo de la Reforma
4   2024-06-28  city scrape             2 bedroom apt. deco bldg, Condesa

  host_name  host_since                host_verifications  \
0     Marco  2013-01-21                ['email', 'phone']
1      Dici  2010-06-28  ['email', 'phone', 'work_email']
2  Fernando  2010-08-09  ['email', 'phone', 'work_email']
3   Martina  2013-01-09                ['email', 'phone']
4  Nicholas  2011-01-04                ['email', 'phone']

  host_has_profile_pic host_identity_verified neighbourhood_cleansed  \
0                    t                      t             Cuauhtémoc
1                    t                      t  Cuajimalpa de Morelos
2                    t                      t             Cuauhtémoc
3                    t                      t         Miguel Hidalgo
4                    t                      t             Cuauhtémoc

               property_type        room_type  \
0         Entire rental unit  Entire home/apt
1               Entire villa  Entire home/apt
2                Entire home  Entire home/apt
3  Entire serviced apartment  Entire home/apt
4         Entire rental unit  Entire home/apt

                                           amenities calendar_last_scraped  \
0  ["40 inch HDTV with Amazon Prime Video, Netfli...            2024-06-28
1  ["Hot water", "Washer", "Bed linens", "Wifi", ...            2024-06-27
2  ["Wifi", "Coffee maker: Nespresso", "Host gree...            2024-06-28
3  ["Wifi", "Host greets you", "Coffee maker", "S...            2024-06-28
4  ["Wifi", "Coffee maker", "Sound system", "Clot...            2024-06-28

  instant_bookable
0                f
1                f
2                f
3                t
4                f

##Crear dos dataframes para ver cuales son cualitativas y cuantitativas

In [125]:
 #Cuantitativas de numeros
cuantitativas = data2[['scrape_id','host_id','host_response_rate','host_listings_count','host_total_listings_count','latitude','longitude','accommodates','minimum_nights','maximum_nights','minimum_minimum_nights','availability_60','availability_90','availability_365','number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d','calculated_host_listings_count','calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms','host_acceptance_rate','bathrooms','bedrooms','beds','price','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value','reviews_per_month']]
cualitativas = data2[['last_scraped','source','name','host_name','host_since','host_verifications','host_has_profile_pic','host_identity_verified','neighbourhood_cleansed','property_type','room_type','amenities','calendar_last_scraped','instant_bookable','host_location','description','host_response_time','host_is_superhost','bathrooms_text','has_availability','first_review','last_review','host_verifications','host_has_profile_pic','host_identity_verified','neighbourhood_cleansed','bathrooms_text','amenities']]

In [126]:
cualitativas.info()
cuantitativas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   last_scraped            26536 non-null  object
 1   source                  26536 non-null  object
 2   name                    26536 non-null  object
 3   host_name               26536 non-null  object
 4   host_since              26536 non-null  object
 5   host_verifications      26536 non-null  object
 6   host_has_profile_pic    26536 non-null  object
 7   host_identity_verified  26536 non-null  object
 8   neighbourhood_cleansed  26536 non-null  object
 9   property_type           26536 non-null  object
 10  room_type               26536 non-null  object
 11  amenities               26536 non-null  object
 12  calendar_last_scraped   26536 non-null  object
 13  instant_bookable        26536 non-null  object
 14  host_location           26536 non-null  object
 15  description             26536 non-null  object
 16  host_response_time      26536 non-null  object
 17  host_is_superhost       26536 non-null  object
 18  bathrooms_text          26536 non-null  object
 19  has_availability        26536 non-null  object
 20  first_review            26536 non-null  object
 21  last_review             26536 non-null  object
 22  host_verifications      26536 non-null  object
 23  host_has_profile_pic    26536 non-null  object
 24  host_identity_verified  26536 non-null  object
 25  neighbourhood_cleansed  26536 non-null  object
 26  bathrooms_text          26536 non-null  object
 27  amenities               26536 non-null  object
dtypes: object(28)
memory usage: 5.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 34 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   scrape_id                                     26536 non-null  int64
 1   host_id                                       26536 non-null  int64
 2   host_response_rate                            26536 non-null  float64
 3   host_listings_count                           26536 non-null  int64
 4   host_total_listings_count                     26536 non-null  int64
 5   latitude                                      26536 non-null  float64
 6   longitude                                     26536 non-null  float64
 7   accommodates                                  26536 non-null  int64
 8   minimum_nights                                26536 non-null  int64
 9   maximum_nights                                26536 non-null  int64
 10  minimum_minimum_nights                        26536 non-null  int64
 11  availability_60                               26536 non-null  int64
 12  availability_90                               26536 non-null  int64
 13  availability_365                              26536 non-null  int64
 14  number_of_reviews                             26536 non-null  int64
 15  number_of_reviews_ltm                         26536 non-null  int64
 16  number_of_reviews_l30d                        26536 non-null  int64
 17  calculated_host_listings_count                26536 non-null  int64
 18  calculated_host_listings_count_entire_homes   26536 non-null  int64
 19  calculated_host_listings_count_private_rooms  26536 non-null  int64
 20  calculated_host_listings_count_shared_rooms   26536 non-null  int64
 21  host_acceptance_rate                          26536 non-null  float64
 22  bathrooms                                     26536 non-null  float64
 23  bedrooms                                      26536 non-null  float64
 24  beds                                          26536 non-null  float64
 25  price                                         26536 non-null  float64
 26  review_scores_rating                          26536 non-null  float64
 27  review_scores_accuracy                        26536 non-null  float64
 28  review_scores_cleanliness                     26536 non-null  float64
 29  review_scores_checkin                         26536 non-null  float64
 30  review_scores_communication                   26536 non-null  float64
 31  review_scores_location                        26536 non-null  float64
 32  review_scores_value                           26536 non-null  float64
 33  reviews_per_month                             26536 non-null  float64
dtypes: float64(16), int64(18)
memory usage: 6.9 MB